#!/usr/bin/env bun
/**
 * Generate the Open Graph share cards.
 *
 *     bun scripts/make-og.mjs              # every card
 *     bun scripts/make-og.mjs home about   # just these
 *
 * WHY THIS EXISTS. The first on-brand cards were generated by hand and the
 * template was thrown away, so five cards kept shipping the pre-rebrand
 * terracotta style for a week, and `home.png` — the fallback on fourteen pages,
 * including the front page — carried a HEADLINE from a positioning we had
 * already retired. Nobody saw it, because the only place a share card is
 * visible is somebody else's feed (site audit, 2026-08-29).
 *
 * Two rules hold this together:
 *   1. Colours are READ from src/styles/global.css, never retyped here. A token
 *      change reaches the cards on the next run; a hex typed into this file
 *      would be a colour no design gate can audit (rules/design-system.md §1).
 *   2. The wordmark is READ from src/components/SiteLogo.astro, so the lockup
 *      cannot drift from the site's own.
 *
 * After regenerating, the file is bytes on disk that no build step touches —
 * commit it, and remember that Telegram, LinkedIn and X cache a card per URL
 * for a long time. A changed image at an unchanged URL may keep serving stale
 * to them; renaming the file is the only reliable cache-buster.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { chromium } from "playwright";

const HERE = dirname(fileURLToPath(import.meta.url));
const SITE = resolve(HERE, "..");
const OUT_DIR = join(SITE, "public", "assets", "og");
const TEMPLATE = join(HERE, "og-template.html");

const die = (msg) => {
  console.error(`make-og: ${msg}`);
  process.exit(1);
};

/** Pull the design tokens out of @theme so the cards cannot drift from the site. */
function tokens() {
  const css = readFileSync(join(SITE, "src", "styles", "global.css"), "utf8");
  const need = ["paper", "ink", "ink-soft", "ink-faint", "yes-deep"];
  const out = {};
  for (const name of need) {
    const m = css.match(new RegExp(`--color-${name}:\\s*(#[0-9a-fA-F]{3,8})`));
    if (!m) die(`--color-${name} not found in global.css @theme`);
    out[name] = m[1];
  }
  return out;
}

/** The brand lockup, lifted verbatim from the component the site renders. */
function lockupSvg() {
  const src = readFileSync(join(SITE, "src", "components", "SiteLogo.astro"), "utf8");
  const m = src.match(/<svg[\s\S]*<\/svg>/);
  if (!m) die("no <svg> found in src/components/SiteLogo.astro");
  return m[0]
    .replace(/\sclass=\{[^}]*\}/g, "")
    .replace(/\srole="img"/, "")
    .replace(/\saria-label="[^"]*"/, "");
}

/**
 * The cards. `accent` is the tail of the headline that goes green; keep it to
 * one clause, the way the site's own hero does.
 *
 * Copy rules that apply here as much as to a page (BRAND.md): no long dashes,
 * no naming of other companies' products, start from the reader's problem, and
 * never promise something the page behind the card does not deliver.
 */
const CARDS = {
  home: {
    file: "home.png",
    eyebrow: "your business · inside claude and chatgpt",
    headline: "900 million people already live in AI chats.",
    accent: "We bridge your business to them.",
    blurb:
      "An MCP connector that puts your bookings, orders and support right inside the conversation.",
    url: "yesmcp.com",
    pill: "free scenario map first",
    headlineSize: 58,
  },
  "home-ua": {
    file: "home-ua.png",
    eyebrow: "ваш бізнес · у claude і chatgpt",
    headline: "900 мільйонів людей уже живуть у ШІ-чатах.",
    accent: "Ми будуємо міст до вашого бізнесу.",
    blurb:
      "MCP-конектор, з яким запис, замовлення і підтримка працюють просто в розмові.",
    url: "yesmcp.com/ua",
    pill: "спершу мапа сценаріїв",
    // Ukrainian runs longer than the English line at the same point size and
    // pushed the blurb into the footer at 56px.
    headlineSize: 50,
  },
  // Renamed from about.png on 2026-08-30 (K1 person-first rewrite): share
  // platforms cache a card BY URL, so new content needs a new filename.
  about: {
    file: "about-serhii.png",
    eyebrow: "who builds yesmcp",
    headline: "Serhii Kravchenko.",
    accent: "I build agent systems.",
    blurb:
      "Two years full-time in agent systems, in Claude Code since its first day. A live connector, a weekly census, measured notes.",
    url: "yesmcp.com/about",
    pill: "",
  },
  "about-ua": {
    file: "about-serhii-ua.png",
    eyebrow: "хто будує yesmcp",
    headline: "Сергій Кравченко.",
    accent: "Я будую агентні системи.",
    blurb:
      "Два роки повний день в агентних системах, у Claude Code з першого дня. Живий конектор, щотижневий перепис, виміряні нотатки.",
    url: "yesmcp.com/ua/about",
    pill: "",
  },
  spec: {
    file: "spec.png",
    eyebrow: "engineering notes",
    headline: "The MCP spec shipped",
    accent: "one day after its SDK",
    blurb:
      "A stateless protocol, a twelve-month deprecation clock, and an SDK published the day before that still tops out on the older version.",
    url: "yesmcp.com/writing",
    pill: "from production",
  },
  injection: {
    file: "injection.png",
    eyebrow: "engineering notes",
    headline: "Your tool results are being",
    accent: "read as an attack",
    blurb:
      "We put behaviour rules in the text our tools returned. The host warned our own user about injected instructions. Why the detector was right.",
    url: "yesmcp.com/writing",
    pill: "from production",
  },
  channels: {
    file: "channels.png",
    eyebrow: "engineering notes",
    headline: "What the host",
    accent: "doesn't deliver",
    blurb:
      "A field guide to the channels between an MCP server and the model: which arrive, which silently do not, and what each one costs.",
    url: "yesmcp.com/writing",
    pill: "from production",
  },
};

const asked = process.argv.slice(2);
const names = asked.length ? asked : Object.keys(CARDS);
for (const n of names) if (!CARDS[n]) die(`unknown card '${n}'. Known: ${Object.keys(CARDS).join(", ")}`);

const t = tokens();
const svg = lockupSvg();

mkdirSync(OUT_DIR, { recursive: true });

const browser = await chromium.launch();
const page = await browser.newPage({
  viewport: { width: 1200, height: 630 },
  deviceScaleFactor: 1,
});

for (const name of names) {
  const card = CARDS[name];
  await page.goto(pathToFileURL(TEMPLATE).href, { waitUntil: "load" });

  await page.evaluate(
    ({ card, t, svg }) => {
      const root = document.documentElement.style;
      root.setProperty("--paper", t.paper);
      root.setProperty("--ink", t.ink);
      root.setProperty("--ink-soft", t["ink-soft"]);
      root.setProperty("--ink-faint", t["ink-faint"]);
      root.setProperty("--yes-deep", t["yes-deep"]);
      if (card.headlineSize) root.setProperty("--headline-size", `${card.headlineSize}px`);

      document.getElementById("lockup").innerHTML = svg;
      document.getElementById("eyebrow").textContent = card.eyebrow;
      const h = document.getElementById("headline");
      h.textContent = card.headline;
      if (card.accent) {
        const span = document.createElement("span");
        span.className = "accent";
        span.textContent = ` ${card.accent}`;
        h.appendChild(span);
      }
      document.getElementById("blurb").textContent = card.blurb;
      document.getElementById("url").textContent = card.url;
      document.getElementById("pill").textContent = card.pill ?? "";
    },
    { card, t, svg },
  );

  // Fonts are @font-face'd from disk; screenshotting before they resolve
  // silently produces a card in the fallback face, which looks almost right.
  await page.evaluate(() => document.fonts.ready);

  const buf = await page.screenshot({ type: "png" });
  const dest = join(OUT_DIR, card.file);
  writeFileSync(dest, buf);
  console.log(`  ${card.file}  ${(buf.length / 1024).toFixed(1)} KB`);
}

await browser.close();
console.log(`make-og: wrote ${names.length} card(s) to public/assets/og/`);
